language: python

python:
 - 2.7

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -q --use-mirrors cffi; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -q --use-mirrors cython; fi
  - pip install -U setuptools
  - pip install -r requirements.txt

install:
 - pip install .

script:
 - make test
 - make coverage
